### ISSUE TITLE
Repo split

### ISSUE THREAD

**Issue by ivannieto** [VigoBrain/VigoBrain#3]
Me acabo de fijar al clonar el repo para revisar los papers de la charla de @daavoo en Gradiant, que es una carpeta dentro del repo básico de unión al grupo.

¿No tendría sentido crear un repositorio específico para cada charla? De ese modo tenemos todo separado. A medida que vaya creciendo y pase el tiempo, este repo VigoBrain puede convertirse en un monstruo de tamaño.

**Comment by daavoo** [comment]
Let's debate.

En teoría este repo es el repo central, no es el "repo de unión". 

El sistema de unión es mediante la issue #1 .

La idea era que este repo fuese el córtex donde además de la de unión (que siempre estará abierta) se irían abriendo y cerrando otras issues para anunciar charlas y demás.

Puede tener sentido crear un repo para cada charla aunque a mi me gusta más tenerlo centralizado en un solo repo. 

Bajo mi punto de vista prefiero tener un "monstruo" de repo con una carpeta /turras llena de subcarpetas a tener una organización "monstruosa" llena de repositorios donde lo único que hay en cada repo son los materiales de una charla. Pero es una opinión personal.

@VigoBrain/members Que las bases se pronuncien :open_hands:

**Comment by daavoo** [comment]
De todas formas hay varias cosas en la carpeta que subí yo que no son necesarias y hacen que pese la leche. A borrarlas me pongo

**Comment by ivannieto** [comment]
Ese es justo el caso. A medida que crezca, por imágenes, datasets, o cualquier tipo de necesidad de cada charla/proyecto/whatever, puede acabar convirtiéndose en una carpeta mayor de 1GB (con lo que conlleva).

Otra opción sería establecer unas directrices en el README para que cualquier persona que llegue al repo (sea cual sea su condición), sepa clonar el proyecto(directorio) que quiera.

```bash
# Inicializar un nuevo repositorio de git
mkdir <repo>
cd <repo>
git init
git remote add -f origin <url>
git config core.sparseCheckout true

# Le decimos a sparse-checkout los directorios a clonar
echo "quiero/este/directorio" >> .git/info/sparse-checkout
echo "este/otro" >> .git/info/sparse-checkout

# Actualizar master, contendrá los directorios que hayamos definido
git pull origin master
```

**Comment by daavoo** [comment]
Buena idea lo de explicar en el README.

Yo creo que con las directrices + activar https://git-lfs.github.com vamos que chutamos para petar el repo de subcarpetas

**Comment by jjmontesl** [comment]
Yo personalmente creo que esto es marear la perdiz. La filosofía unix/git es repos pequeños para proyectos individuales. A mí me da igual usar sparse checkout o bajarme un repo enorme pero si lo que queremos es tener acceso individual a cada charla, lo normal sería crear un repo para cada una.

También dificulta el uso normal de un repo. Si la charla 4 depende de código de la charla 2, pero la charla 2 ha sido modificada desde entonces, es fácil clonar el repo 2 y hacer un checkout del commit que nos interesa. No tan cómodo si está todo en el mismo repo.

Usar un único repo para coordinar las charlas via GitHub issues lo veo bien, aunque lo normal es usar una lista de correo. Las issues de GitHub no son un formato estándar, y los comentarios se pueden modificar retroactivamente.

**Comment by jjmontesl** [comment]
BTW, tampoco entiendo los mensajes de los commits. Son bonitos pero no dicen mucho respecto a qué cambios introduce cada commit :-?.

**Comment by daavoo** [comment]
@jjmontesl Ten en cuenta una cosa y es que aquí estamos probando a usar un repo de GitHub para cosas que no tienen que ver con el uso para el que fueron diseñados; puede salir bien o mal.

Las filosofías para el desarrollo de proyectos de código no tienen por qué tener que aplicarse a un repo de gestión con contenidos de charlas.

Por ejemplo al supuesto caso de dependencia de código entre charlas no le encuentro el sentido, los materiales para cada charla deberían ser autosuficientes. 

Tampoco creo que importe que los commits expliquen queéhacen porque el repo no va de código. Pero si no queda más remedio cesaré los emojis. Nadie apoya mi [git-emoji-flow](https://gist.github.com/daavoo/b9c0f3c2c91ade2820f05c35940acaa6
) :)

--- 

A mí tanto me da una organización con muchos repos o un repo con muchas subcarpetas. No soy firme defensor de ninguna, simplemente opino que igual tampoco es algo tan loco tener todo en mismo repo. 

Por ejemplo el señor Obijuan tiene este repo: https://github.com/Obijuan/myslides y parece no haber explotado.

---

Respecto a las Issues. En este caso sí que firmemente defiendo centralizar la gestión en un solo sitio, y que todo lo que se haga pueda ser visto por cualquiera, miembro o no miembro.

Al final al tener varios canales de comunicación siempre se dispersa la información a la que accede cada uno y el hecho de que tengas que registrarte para poder ver lo que se comenta me parece que le da a la gestión cierta opacidad (No niego que haya ocasiones en las que la privacidad sea necesaria, pero para eso ya tenemos slack?)

Lo de que se puedan modificar los comentarios en principio no me parece preocupante. 

Si todo el mundo quiere empezar a gestionar por lista de correo, pues me parece bien.

@VigoBrain/members

**Comment by jjmontesl** [comment]
Para mí una lista de correo o un Meetup tiene la ventaja de que llega a mi correo, apropiadamente etiquetada (y que atiendo más disciplinadamente que las issues). 

Las issues tienen la desventaja de que hasta que un@ no se suscribe a cada una ellas no ve los mensajes, así que una issue para cada reunión implicaría (si no me equivoco) que a la gente no le llegarían los mensajes si no van en primer lugar a suscribirse a la issue, o siguen a la organización o al repo (que igual es un incordio para algun@s).

Dicho todo esto, a mí tb me da igual el mecanismo, sólo digo que igual estamos reinventando la rueda para cosas que están bien exploradas.

**Comment by daavoo** [comment]
La idea de emplear la organización de GitHub con teams es que con una mención a "@VigoBrain/members" les debería de llegar un correo a todos los miembros y con "@VigoBrain/staff" pues solo a gente del "staff". 

Lo de etiquetado ya depende de cómo cada uno como tenga montado el tinglado supongo, a mi las issues de github me llegan etiquedadas correctamente y por repositorio y sin embargo meetup lo tengo como "social" y muchas veces no le hago caso.

De todas maneras, la burocracia no es mi pasión. Si se prefiere usar meetup o lista de correo, bienvenido sea. 

Simplemente me pareció a mí, como persona vaga, más fácil de gestionar todo a través de GitHub que tener un repo para las charlas, un meetup para nosequé, el slack para lo otro y la lista de correo para lo último.

**Comment by ivannieto** [comment]
Creo que se desvía la atención de esta issue en concreto, y se debería abrir uno específico para tratar el cómo se llega a la gente.

Aquí un partidario del split de repos.

**Comment by daavoo** [comment]
Olrait. Qué os parece usar releases de Github para publicar los contenidos de las charlas.

Las releases te dejan adjuntar un .zip y no influyen a la hora de clonar el repo y que se puede descargar directamente.

Ahora mismo acabo de subir la única turra que había como prueba.

Así simplemente podemos tener en turras un README como el que hay ahora que apunta a la url de la release correspondiente.

**Comment by ivannieto** [comment]
Creo que con la solución dada se podría cerrar este issue y si alguien siente que no está a gusto con esta forma, que lo reabra.

:fist_raised:
