### ISSUE TITLE
2017-09-27

### ISSUE THREAD

**Issue by daavoo** [VigoBrain/VigoBrain#5]
Arrancamos a tope con la cope. Primera reunión:

# Miércoles 27
### [Kaleido Coworking // García Barbón 27 Interior bajo · Vigo](https://www.google.es/maps/place/Kaleido+Coworking+Center/@42.2378185,-8.7177254,17.5z/data=!4m5!3m4!1s0x0:0xd3efad4529b8b71e!8m2!3d42.2374301!4d-8.717658)

---

La reunión constará de 3 partes:

# 1 - Charla
## Introducción a los algoritmos genéticos.
By [Carlos Groba](https://twitter.com/cgroba)

# 2 - Asamblea
## ¿¿¿Qué queremos hacer en VigoBrain??? 
Traed vuestras propuestas.

# 3 - Ingesta de refrigerios

En algún lugar cercano. (El Porto santo sigue cerrado?)

---

No es obligatorio confirmar asistencia pero estaría bien que los que estén seguros de que van a venir dejen un comentario del estilo: EU VOU!. 

---

Si queréis recibir notificaciones de reuniones y otras noticias fascinantes podéis uniros a la organización en el siguiente enlace:

https://github.com/VigoBrain/VigoBrain/issues/1

@VigoBrain/members

**Comment by daavoo** [comment]
EU VOU!

![partyhard](https://user-images.githubusercontent.com/12677733/30495775-93d71c8e-9a4d-11e7-825b-f542719354c8.gif)

**Comment by DiegoReiriz** [comment]
EU VOU!.

**Comment by daniperfer** [comment]
Eu vou!

**Comment by jjmontesl** [comment]
+1

**Comment by Adurba** [comment]
Eu vouu!!

**Comment by AlbertoCastelo** [comment]
Eu vou tamén!

**Comment by mlamelas** [comment]
+1

**Comment by ivannieto** [comment]
Laik y me suscribo

**Comment by felixgomez** [comment]
+1

**Comment by pgonzalezf** [comment]
+1!

**Comment by jcleira** [comment]
🕺

**Comment by davidjimenezphd** [comment]
+1

**Comment by jorgenaya** [comment]
+1

**Comment by kusflo** [comment]
+1

**Comment by ivannieto** [comment]
🤖

**Comment by cabokabo** [comment]
+1

**Comment by daavoo** [comment]
@VigoBrain/members 

Presentaciones de la charla en:
https://github.com/VigoBrain/VigoBrain/releases/tag/0.0.2
